
on:
  push:
    branches: 
      - master


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Lint
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint
          affected: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Test
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: test
          affected: true


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Build
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build
          affected: true

  publish:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - test
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Build
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build
          affected: true
      - run: |
          for LIBRARY in $(npm run nx affected:libs --base=$last_version --head=$current_version --plain | awk 'NR > 2 && $1 != "Done" { print $1 }')
          do
            cd ./dist/packages/$LIBRARY
            npm publish --access public
            cd ..
            cd ..
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
