on:
  push:
    branches: 
      - master
    paths-ignore: 
      - packages/core/**
      - packages/forms-example/**
      - packages/forms-example-e2e/**


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Lint
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint
          projects: react

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Test
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: test
          projects: react


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Build
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build
          projects: react

  publish:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - test
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Build
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build
          projects: react
      - run: npm publish --access public
        working-directory: dist/packages/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
